@Server_HostAddress = http://localhost:5221

# GET {{Server_HostAddress}}/weatherforecast/
# Accept: application/json

### 

GET {{Server_HostAddress}}/api/Account/verify-2fa?email=hello@email.com&code=
Accept: application/json

###

POST https://leoums.dev/api/UMS/check-user
Content-Type: application/json
Accept: application/json

{
  "email": "email",
  "password": "password"
}
